# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: attestation-container.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'attestation-container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61ttestation-container.proto\x12\x15\x61ttestation_container\".\n\x17\x46\x65tchAttestationRequest\x12\x13\n\x0breport_data\x18\x01 \x01(\x0c\"e\n\x15\x46\x65tchAttestationReply\x12\x13\n\x0b\x61ttestation\x18\x01 \x01(\x0c\x12\x1d\n\x15platform_certificates\x18\x02 \x01(\x0c\x12\x18\n\x10uvm_endorsements\x18\x03 \x01(\x0c\x32\x8a\x01\n\x14\x41ttestationContainer\x12r\n\x10\x46\x65tchAttestation\x12..attestation_container.FetchAttestationRequest\x1a,.attestation_container.FetchAttestationReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attestation_container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FETCHATTESTATIONREQUEST']._serialized_start=54
  _globals['_FETCHATTESTATIONREQUEST']._serialized_end=100
  _globals['_FETCHATTESTATIONREPLY']._serialized_start=102
  _globals['_FETCHATTESTATIONREPLY']._serialized_end=203
  _globals['_ATTESTATIONCONTAINER']._serialized_start=206
  _globals['_ATTESTATIONCONTAINER']._serialized_end=344
# @@protoc_insertion_point(module_scope)
